<H1 style = "color : blue"> NumPy - Creating Numpy Arrays </H1>

## Table of Content
1. <b>Creating Numpy Arrays:</b>
 - The following ways are commonly used when you know the size of the array beforehand:
     * ```np.ones()```: 
         * Create array of 1s<br>
         * np.ones(5,dtype = int)
         * 2 Dimensional Array : np.ones((3,2),dtype = int)
     * ```np.zeros()```: 
         * Create array of 0s
         * np.ones(5,dtype = int)
         * 2 Dimensional Array : np.zeros((3,2),dtype = int)
     * ```np.random.random()```: 
         * Create array of random numbers
         * Syntax: np.random.random([3,3]) creates 2 dimensional array
     * ```np.arange()```: 
         * Create array with increments of a fixed step size
         * np.arange(3) results array([0, 1, 2])
         * np.arange(2,5) results array([2, 3, 4])
         * np.arange(3,35,2) results array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
         * np.arange(5,51,5) results array of multiple of 5 for first 10
     * ```np.linspace()```: 
         * Create array of fixed length
         * np.linspace(1,10,20) result array between 1 to 10 for given number of size calculating steps by themselves.
     * ```np.full()```: 
         * Create a constant array of any number ‘n’
         * Syntax = full(shape, fill_value, dtype=None, order='C')
         * np.full(10,2) results array of 10 size with value as 2
     * ```np.tile()```: 
         * Create a new array by repeating an existing array for a particular number of times
         * Syntax = tile(A, reps)
         * np.tile(2,3) returns array([2, 2, 2])
         * np.tile(2,(3,4)) returns array of 3 row and 4 column with all value as 2
         * np.tile([1,2,3],(2,2)) returns 2 * 2 array with given array in it
     * ```np.eye()```: 
         * Create an identity matrix of any dimension
         * Syntax : eye(N, M=None, k=0, dtype=<class 'float'>, order='C') k = Index of the diagonal
         * np.eye(2, dtype=int) return identity matrix of 2 * 2
     * ```np.random.randint()```: 
         * Create a random array of integers within a particular range
         * Syntax : randint(low, high=None, size=None, dtype='l')
         * np.random.randint(5,size = 10) returns 10 size array with Random int between 0 to 4
         * np.random.randint(5,50,size = 10) returns 10 size array with Random int between 5 to 50
            
        
 

In [42]:
import numpy as np

##### Tip: Use help to see the syntax when required

In [43]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

##### Creating a 1 D array of ones

In [44]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

##### Notice that, by default, numpy creates data type = float64



In [45]:
arr.dtype

dtype('float64')

##### Can provide dtype explicitly using dtype


In [46]:
arr = np.ones(5,dtype = int)
arr

array([1, 1, 1, 1, 1])

In [47]:
arr.dtype

dtype('int32')

##### Creating a 5  x 3 array of ones


In [48]:
np.ones((5,3), dtype  = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##### Creating array of zeros

In [49]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [50]:
np.zeros((3,3,3), dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [51]:
list(range(1,5))

[1, 2, 3, 4]

In [52]:
np.arange(3)

array([0, 1, 2])

In [53]:
np.arange(3.0)

array([0., 1., 2.])

In [54]:
np.arange(2,5)

array([2, 3, 4])

##### Notice that 3 is included, 35 is not, as in standard python lists

From 3 to 35 with a step of 2

In [55]:
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

##### Array of random numbers 


In [56]:
np.random.randint(5,size = 10)

array([1, 3, 3, 4, 1, 2, 3, 1, 3, 3])

In [57]:
np.random.randint(5.0,size = 10)

array([3, 3, 0, 2, 2, 0, 0, 3, 1, 2])

In [58]:
np.random.randint(5,50,size = 10)

array([26, 12, 15, 25, 38, 32, 42, 12, 27, 21])

In [59]:
np.random.randint(5,50,size = 10,dtype = int)

array([33, 22, 36, 46, 21, 16, 13, 26, 35, 49])

In [60]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo

## Excercise ##

<h2 style = "color : Brown">Array 'arange' Function</h2>
Description:<br>
Create an array of first 10 multiples of 5 using the 'arange' function.


In [61]:
import numpy as np
array_multipleof5 = np.arange(5,51,5)

print(array_multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


In [62]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

##### 2D Array of random numbers 


In [63]:
np.random.random([3,3])

array([[0.10930411, 0.67695288, 0.44813358],
       [0.25722523, 0.68418428, 0.32310393],
       [0.70469085, 0.74566642, 0.08914952]])

In [64]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



###### Sometimes, you know the length of the array, not the step size

Array of length 20 between 1 and 10

In [65]:
#np.random.randint(1,10,size = 20)
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [66]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

<h2 style = "color : Sky blue"> Exercises </h2>



Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

In [67]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [68]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values to

In [69]:
np.tile(2,3)

array([2, 2, 2])

In [70]:
np.tile(2,(3,4))

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [71]:
np.tile([1,2,3],(2,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [72]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [73]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [74]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

### Create border array ###
Description : Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

In [75]:
# Read the variable from STDIN
n = int(input())

import numpy as np

# Create an 'n*n' array of all ones

arr = np.ones((n,n),dtype = int)

# Fill the array with zeroes from second index (i.e. index 1) to second last index.
# Do this for both row indices and column indices

#1:-1 will going to exclude first and last record
arr[1:-1,1:-1] = 0

print(arr)

# Print the array created


4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [76]:
np.arange(3,35,2) 

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])